version: "3.8"

services:
  db-clinic:
    image: 'postgres:14.12-alpine3.19'
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db-clinic-volume:/var/lib/postgres

  backend-clinic:
    image: erry-az/backend-clinic
    depends_on:
      - db-clinic
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:8080
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:postgresql://db-clinic:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
          "spring.datasource.username" : "$POSTGRESDB_USER",
          "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.datasource.type": "com.zaxxer.hikari.HikariDataSource",
          "spring.datasource.hikari.minimum-idle": "10",
          "spring.datasource.hikari.maximum-pool-size": "50"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  frontend-clinic:
    image: erry-az/frontend-clinic
    env_file: ./.env
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "${FE_LOCAL_PORT}:4200"

volumes:
  db-clinic-volume:
